# Generated by Django 4.2.29 on 2026-08-20 01:06

import core.fields
import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedicalcontrolmission',
            name='percentage_four',
            field=models.CharField(blank=True, db_column='PercentageFour', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='historicalmedicalcontrolmission',
            name='percentage_one',
            field=models.CharField(blank=True, db_column='PercentageOne', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='historicalmedicalcontrolmission',
            name='percentage_three',
            field=models.CharField(blank=True, db_column='PercentageThree', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='historicalmedicalcontrolmission',
            name='percentage_two',
            field=models.CharField(blank=True, db_column='PercentageTwo', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='medicalcontrolmission',
            name='percentage_four',
            field=models.CharField(blank=True, db_column='PercentageFour', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='medicalcontrolmission',
            name='percentage_one',
            field=models.CharField(blank=True, db_column='PercentageOne', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='medicalcontrolmission',
            name='percentage_three',
            field=models.CharField(blank=True, db_column='PercentageThree', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='medicalcontrolmission',
            name='percentage_two',
            field=models.CharField(blank=True, db_column='PercentageTwo', max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalFilteredClaimsForMission',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('from_rejected_to_valuated', models.BooleanField(blank=True, db_column='RejectedToValuated', null=True)),
                ('audit_explanation', models.CharField(blank=True, db_column='AuditExplanation', max_length=500, null=True)),
                ('audited', models.BooleanField(blank=True, db_column='Audited', null=True)),
                ('claim_category', models.CharField(blank=True, db_column='ClaimCategory', max_length=1, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('claim', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='claim.claim')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medical_controller.medicalcontrolmission')),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical filtered claims for mission',
                'verbose_name_plural': 'historical filtered claims for missions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FilteredClaimsForMission',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('from_rejected_to_valuated', models.BooleanField(blank=True, db_column='RejectedToValuated', null=True)),
                ('audit_explanation', models.CharField(blank=True, db_column='AuditExplanation', max_length=500, null=True)),
                ('audited', models.BooleanField(blank=True, db_column='Audited', null=True)),
                ('claim_category', models.CharField(blank=True, db_column='ClaimCategory', max_length=1, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='claim.claim')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mission_health_facilities', to='medical_controller.medicalcontrolmission')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblFilteredClaimsForMission',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
    ]
